### ISSUE TITLE
Hello nothing is working

### ISSUE THREAD

**Issue by huora3** [PekingSecureSolutions/WilmaLockerV2#1]
This is the worst product in history please release peking mesenger already

**Comment by PekingSolutions** [comment]
Thank you for the comment!

Here at PekingSolutions™, our workers take these issues very seriously. After a detailed investigation on your issue we have found the reasoning behind it. WilmaLockerV2™ has a newly implemented ["Anti-Broke"](https://www.ramseysolutions.com/saving/how-to-make-extra-money) feature. This feature makes the program unusable for a without any richness in their operating system. 

Kind Regards, PekingSolutions™

**Comment by huora3** [comment]
Thank you for this comment for this and i hope to see you soon mr. bitch
